if(NOT DEFINED INPUT OR NOT DEFINED OUTPUT OR NOT DEFINED SYMBOL)
    message(FATAL_ERROR "embed_spirv.cmake requires INPUT, OUTPUT, and SYMBOL")
endif()

file(READ "${INPUT}" _spirv HEX)
string(LENGTH "${_spirv}" _hex_length)
math(EXPR _remainder "${_hex_length} % 8")
if(NOT _remainder EQUAL 0)
    message(FATAL_ERROR "SPIR-V byte length is not a multiple of four: ${INPUT}")
endif()

set(_words "")
math(EXPR _last "${_hex_length} - 8")
if(_last GREATER_EQUAL 0)
    foreach(_offset RANGE 0 ${_last} 8)
        string(SUBSTRING "${_spirv}" ${_offset} 2 _b0)
        math(EXPR _next "${_offset} + 2")
        string(SUBSTRING "${_spirv}" ${_next} 2 _b1)
        math(EXPR _next "${_offset} + 4")
        string(SUBSTRING "${_spirv}" ${_next} 2 _b2)
        math(EXPR _next "${_offset} + 6")
        string(SUBSTRING "${_spirv}" ${_next} 2 _b3)
        string(APPEND _words "    0x${_b3}${_b2}${_b1}${_b0}U,\n")
    endforeach()
endif()

set(_header "#pragma once\n\n#include <cstdint>\n\nnamespace dsmvc::vulkan_detail::embedded {\ninline constexpr std::uint32_t ${SYMBOL}[] = {\n${_words}};\n} // namespace dsmvc::vulkan_detail::embedded\n")
file(WRITE "${OUTPUT}" "${_header}")
